#!/usr/bin/env bash
# Smoke test: run the CLI and the Stop hook against a throwaway HOME with a
# few fake Claude Code transcripts and check the output.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI="node $ROOT/scripts/cli.js"
HOOK="node $ROOT/scripts/hook-auto-name.js"

export HOME
HOME="$(mktemp -d)"
trap 'rm -rf "$HOME"' EXIT

PROJ="$HOME/.claude/projects/-home-user-demo"
mkdir -p "$PROJ" "$HOME/.claude/projects/-home-user-empty"

U1=aaaaaaaa-1111-4111-8111-111111111111 # normal conversation
U2=bbbbbbbb-2222-4222-8222-222222222222 # array content + malformed line
U3=cccccccc-3333-4333-8333-333333333333 # empty file
U4=dddddddd-4444-4444-8444-444444444444 # starts with a slash command

cat > "$PROJ/$U1.jsonl" <<JSONL
{"parentUuid":null,"isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U1","type":"user","message":{"role":"user","content":"Help me fix the wolt integration timeout bug in the order sync"},"uuid":"11111111-aaaa-4aaa-8aaa-000000000001","timestamp":"2026-08-29T10:00:00.000Z"}
{"parentUuid":"11111111-aaaa-4aaa-8aaa-000000000001","isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U1","type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"Sure, let me look at the sync code first."}]},"uuid":"11111111-aaaa-4aaa-8aaa-000000000002","timestamp":"2026-08-29T10:00:05.000Z"}
{"parentUuid":"11111111-aaaa-4aaa-8aaa-000000000002","isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U1","type":"user","message":{"role":"user","content":[{"type":"text","text":"It is in src/sync.ts"}]},"uuid":"11111111-aaaa-4aaa-8aaa-000000000003","timestamp":"2026-08-29T10:01:00.000Z"}
JSONL

cat > "$PROJ/$U2.jsonl" <<JSONL
{"type":"summary","summary":"Refactor auth middleware","leafUuid":"22222222-bbbb-4bbb-8bbb-000000000001"}
{"parentUuid":null,"isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U2","type":"user","message":{"role":"user","content":[{"type":"text","text":"Refactor the auth middleware to use the new session helper"}]},"uuid":"22222222-bbbb-4bbb-8bbb-000000000001","timestamp":"2026-08-28T09:00:00.000Z"}
this line is not json at all
{"parentUuid":"22222222-bbbb-4bbb-8bbb-000000000001","isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U2","type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"On it."}]},"uuid":"22222222-bbbb-4bbb-8bbb-000000000002","timestamp":"2026-08-28T09:00:05.000Z"}
JSONL

: > "$PROJ/$U3.jsonl"

cat > "$PROJ/$U4.jsonl" <<JSONL
{"type":"file-history-snapshot","messageId":"x","snapshot":{},"isSnapshotUpdate":false}
{"parentUuid":null,"isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U4","type":"user","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. Output will not be shown.</local-command-caveat>"},"isMeta":true,"uuid":"44444444-0000-4000-8000-000000000001","timestamp":"2026-08-30T08:00:00.000Z"}
{"parentUuid":"44444444-0000-4000-8000-000000000001","isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U4","type":"user","message":{"role":"user","content":"<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>"},"uuid":"44444444-0000-4000-8000-000000000002","timestamp":"2026-08-30T08:00:01.000Z"}
{"parentUuid":"44444444-0000-4000-8000-000000000002","isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U4","type":"user","message":{"role":"user","content":"<local-command-stdout>Set model to sonnet</local-command-stdout>"},"uuid":"44444444-0000-4000-8000-000000000003","timestamp":"2026-08-30T08:00:02.000Z"}
{"parentUuid":"44444444-0000-4000-8000-000000000003","isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U4","type":"user","message":{"role":"user","content":[{"type":"text","text":"Add a CHANGELOG to the repo"}]},"uuid":"44444444-0000-4000-8000-000000000004","timestamp":"2026-08-30T08:01:00.000Z"}
{"parentUuid":"44444444-0000-4000-8000-000000000004","isSidechain":false,"cwd":"/home/user/demo","sessionId":"$U4","type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"Done."}]},"uuid":"44444444-0000-4000-8000-000000000005","timestamp":"2026-08-30T08:01:05.000Z"}
JSONL

fail() { echo "FAIL: $*" >&2; exit 1; }
# Assert that $2 contains $1 (after stripping ANSI colors)
assert_contains() {
  local needle="$1" haystack
  haystack="$(printf '%s' "$2" | sed 's/\x1b\[[0-9;]*m//g')"
  case "$haystack" in
    *"$needle"*) ;;
    *) echo "--- output:" >&2; echo "$haystack" >&2; fail "expected to find: $needle" ;;
  esac
}
assert_not_contains() {
  local needle="$1" haystack
  haystack="$(printf '%s' "$2" | sed 's/\x1b\[[0-9;]*m//g')"
  case "$haystack" in
    *"$needle"*) echo "--- output:" >&2; echo "$haystack" >&2; fail "did not expect to find: $needle" ;;
  esac
}

echo "- list"
out="$($CLI list --project demo)"
assert_contains "4 conversation(s)" "$out"
assert_contains "[auto] Help me fix the wolt integration timeout bug in the order..." "$out"
assert_contains "3 msgs" "$out"
assert_contains "[auto] Refactor the auth middleware to use the new session helper" "$out"
assert_contains "[auto] Empty conversation" "$out"
assert_contains "[auto] Add a CHANGELOG to the repo" "$out"   # slash-command lines are skipped
assert_not_contains "Caveat" "$out"
assert_not_contains "<command-name>" "$out"

echo "- list (empty project)"
assert_contains "No conversations found." "$($CLI list --project empty)"

echo "- list (no ~/.claude at all)"
assert_contains "No Claude Code projects found." "$(HOME=$(mktemp -d) $CLI list)"

echo "- search"
out="$($CLI search wolt --project demo)"
assert_contains "1 result(s) for \"wolt\"" "$out"
assert_contains "aaaaaaaa..." "$out"
assert_contains "No conversations matching \"zzz\"" "$($CLI search zzz --project demo)"

echo "- rename / unname (with --project before the positional args)"
assert_contains "Named \"aaaaaaaa...\" → \"Wolt timeout fix\"" "$($CLI rename --project demo aaaa Wolt timeout fix)"
out="$($CLI list --project demo)"
assert_contains "[named] Wolt timeout fix" "$out"
assert_contains "1 result(s) for \"timeout fix\"" "$($CLI search timeout fix --project demo)"
assert_contains "Removed name from \"aaaaaaaa...\"" "$($CLI unname --project demo aaaa)"
assert_contains "No conversation matching \"zzzz\"" "$($CLI name zzzz foo --project demo)"

echo "- auto"
assert_contains "Auto-named 3 conversation(s)" "$($CLI auto --project demo)"
rm "$PROJ/chat-names.json"

echo "- help / unknown command"
assert_contains "Usage:" "$($CLI --help)"
assert_contains "Unknown command \"bogus\"" "$($CLI bogus)"

echo "- Stop hook"
hook() { printf '%s' "$1" | $HOOK; }
out="$(hook "{\"session_id\":\"$U1\",\"transcript_path\":\"$PROJ/$U1.jsonl\",\"cwd\":\"/home/user/demo\",\"hook_event_name\":\"Stop\",\"stop_hook_active\":false}")"
[ "$out" = '{"continue":true}' ] || fail "hook output: $out"
grep -q '"name": "Help me fix the wolt integration timeout bug in the order..."' "$PROJ/chat-names.json" || fail "hook did not name $U1"
grep -q '"auto": true' "$PROJ/chat-names.json" || fail "hook name not flagged auto"

# slash-command session: the caveat/command lines must be skipped
hook "{\"transcript_path\":\"$PROJ/$U4.jsonl\",\"hook_event_name\":\"Stop\"}" > /dev/null
grep -q '"name": "Add a CHANGELOG to the repo"' "$PROJ/chat-names.json" || fail "hook named the slash-command session wrong: $(cat "$PROJ/chat-names.json")"

# already named: must not overwrite
$CLI name bbbb "Keep me" --project demo > /dev/null
hook "{\"transcript_path\":\"$PROJ/$U2.jsonl\",\"hook_event_name\":\"Stop\"}" > /dev/null
grep -q '"name": "Keep me"' "$PROJ/chat-names.json" || fail "hook overwrote a custom name"

# edge cases: must never fail, always answer {"continue":true}
for payload in \
  '{"transcript_path":"/nonexistent/x.jsonl","hook_event_name":"Stop"}' \
  '' \
  'not json' \
  "{\"transcript_path\":\"$PROJ/$U3.jsonl\"}"; do
  out="$(hook "$payload")" || fail "hook exited non-zero for payload: $payload"
  [ "$out" = '{"continue":true}' ] || fail "hook output for payload [$payload]: $out"
done
# the empty transcript must not get a name
grep -q "$U3" "$PROJ/chat-names.json" && fail "hook named an empty transcript"

echo "OK: all smoke tests passed"
